apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      # should be deployed on docker hub to access
      image: arifrahman88/chat-lah-client:latest
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
