version: "3"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL}
    ports:
      - "3000:3000"
    volumes:
      # allow us to do hot reload
      - /app/node_modules
      - ./client:/app
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NODE_PATH=src
    ports:
      - "4000:4000"
    volumes:
      # allow us to do hot reload
      - /app/node_modules
      - ./server:/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
