# https://dev.to/dariansampare/setting-up-docker-typescript-node-hot-reloading-code-changes-in-a-running-container-2b2f

#  Specify base image
FROM node:alpine as build

# Adding folder and copy in container
WORKDIR /app
COPY . .

# Install dependencies
RUN npm install

# Default command
CMD [ "npm", "start:dev" ]